#Logfabric - PostgresSQL

#--Connections-- keeping it low ; use PgBouncer for pooling 
max_connections = 100

#--Memory---
shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 16MB
maintenance_work_mem  = 256MB 

#---WL / Durability ---
wal_level = replica
max_wal_size = 2GB

# --- Timezone ---
timezone = 'UTC'